apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osticket
  template:
    metadata:
      labels:
        app: osticket
    spec:
      containers:
      - name: osticket
        image: vlasis/osticket:latest
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: osticket-mysql
        - name: MYSQL_DATABASE
          value: osticket
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password  
