apiVersion: v1 
kind: Service
metadata:
  name: redis #name of service
  labels:
    name: redis-service 
    app: demo-voting-app #name of application
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:                          #link service to pod
    name: redis-pod
    app: demo-voting-app
                                    

