apiVersion: v1 
kind: Service
metadata:
  name: result-service #name of service
  labels:
    name: result-service 
    app: demo-voting-app #name of application
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:                          #link service to pod
    name: result-app-pod
    app: demo-voting-app
